root:   "/explore/nobackup/projects/ilab/cache/FMF/"
results:   "{root}/results"
cache:     "{root}/cache"
processed: '{root}/processed'

dataset_root:  "/css/merra2/MERRA2_all/"
dataset_files: "Y{year}/M{month}/MERRA2.{freq}_{collection}_{group}.{year}*.nc4"
